# Generated by Django 4.2.16 on 2026-03-30 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Muhammadali', max_length=100)),
                ('owner_title', models.CharField(default='Software Engineer | Django Developer', max_length=200)),
                ('owner_bio', models.TextField(blank=True)),
                ('owner_avatar', models.ImageField(blank=True, null=True, upload_to='owner/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_url', models.URLField(blank=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('youtube_url', models.URLField(blank=True)),
                ('youtube_username', models.CharField(blank=True, max_length=100)),
                ('instagram_url', models.URLField(blank=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('university', models.CharField(blank=True, default='Toshkent Axborot Texnologiyalari Universiteti Samarqand filiali', max_length=300)),
                ('major', models.CharField(blank=True, default='Dasturiy Injiniring', max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Vergul bilan ajrating: Python, Django, FastAPI')),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
